before_deploy:
- test $TRAVIS_TEST_RESULT = 0
after_success:
  - npm run build:dist
branches:
  only:
  - master
env:
- NODE_ENV=production
install:
- npm install
language: node_js
node_js:
- 6
script:
- npm test
deploy:
  provider: heroku
  app: graphql-boilerplate
  skip_cleanup: true
  api_key:
    secure: ${HEROKU_API_KEY}
