before_deploy:
- test $TRAVIS_TEST_RESULT = 0
after_success:
- npm run build:dist
cache:
  directories:
  - node_modules
branches:
  only:
  - master
env:
  matrix:
  - NODE_ENV=production
install:
- npm install
language: node_js
node_js:
- 6
script:
- npm test
deploy:
  provider: heroku
  app: graphql-boilerplate-server
  skip_cleanup: true
  api_key:
    secure: "${HEROKU_API_KEY}"
